# Generated by Django 5.2.7 on 2025-11-05 11:59

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
            ],
        ),
    ]
